name: BlazeSMP
version: '0.0.1-a'
main: org.example.blazesmp.BlazeSMP
api-version: '1.21'
load: STARTUP
authors: [ DaTTV, Freezy, EmrageGHC ]
description: A simple Plugin for a streamer SMP!
website: https://freezy.me
